# Generated by Django 3.2 on 2021-04-23 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='liked_recipes', to='nutrify.UserProfile'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='saved_by',
            field=models.ManyToManyField(null=True, related_name='saved_recipes', to='nutrify.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userrecipes',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='nutrify.userprofile'),
        ),
    ]
