# Generated by Django 3.2 on 2021-04-20 11:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
