# Generated by Django 3.2 on 2021-04-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrify', '0003_recipe_preperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
